# Generated by Django 4.2.5 on 2023-09-19 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_amount_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='link',
        ),
    ]
